base_url = "https://6260.tekelili.dev"

title = "6260 notes"

theme = "radion"

compile_sass = true

build_search_index = false

taxonomies = [
	{ name = "categories", feed = true },
	{ name = "tags", feed = true },
]

[markdown.highlighting]
style = "class"
dark_theme = "material-theme-palenight"
light_theme = "everforest-light"

[extra]
radion_title = "6260 Notes: Happy Dafny"
theme = "toggle"
codeblock = true	
latex = true
comments = false
radion_menu = [
	{ url = "$BASE_URL", name = "Home" },
	{ url = "$BASE_URL/categories", name = "Categories" },
	{ url = "$BASE_URL/tags", name = "Tags" },
]


